# Generated by Django 4.2.6 on 2023-11-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Poster',
            field=models.ImageField(default='null.jpg', upload_to='imgfile'),
        ),
        migrations.AddField(
            model_name='movies',
            name='Video',
            field=models.FileField(default=False, upload_to='videofile'),
        ),
    ]
