# Generated by Django 4.2.6 on 2023-11-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_video_movies_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='discription',
            field=models.CharField(default='no_discription_found', max_length=100),
        ),
    ]
