# Generated by Django 4.2.6 on 2023-11-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('phn_no', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
    ]
