# Generated by Django 4.2.6 on 2023-12-07 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_genre_remove_movies_genre_movies_genre_id'),
        ('projectapp', '0004_comments_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='movie_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.movies'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.signup'),
        ),
    ]
