# Generated by Django 4.2.6 on 2023-12-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_comments_date_time_comments_movie_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
