# Generated by Django 4.2.6 on 2023-12-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_movies_dislike_movies_like'),
        ('projectapp', '0007_comments_is_disliked_comments_is_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.movies')),
                ('user_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.signup')),
            ],
        ),
    ]
